_infografiky/emise/emise-cr-detail.md, _infografiky/emise/emise-cr.md, _infografiky/emise/emise-eu-poradi.md, _infografiky/emise/emise-eu.md, _infografiky/emise/emise-vybrane-staty.md, _infografiky/teploty/koncentrace-co2.md, _infografiky/teploty/teplota-cr-mesice.md, _infografiky/teploty/teplota-cr.md, _infografiky/teploty/trend-teplot-cr.md, _infografiky/teploty/vyvoj-teplotni-anomalie.md, _layouts/infographic.html, assets/css/main.css
* Vo vetve `vice-zdroju-dat` je vylepsenie, ktore umoznuje, aby povodny sdroj obsahoval viac stranok. Ak je zadana len jedna, zobrazuje sa to tak, ako doteraz. Ak je zadanych viac, zobrazi sa dropdown menu (ako pri rozliseni PNG).
* Zaroven sa menila syntax (pomenovanie) odkazovanych dat, v zdrojovych suboroch sa teraz pouziva intuitivnejsie `data-our` a `data-orig`.
=> Moznost vice zdroju dat

.gitignore, .travis.yml, Makefile, _config.yml, utils/test.rb
* Testy přesunuty do samostatného ruby souboru.
* Testy mají prodloužený timeout na externí odkazy (resolves #294).
* Zapnuto cachováńí kontroly externích odkazů (7 dní).
* Cache jednotně umístěna do složky .cache.
=> Vylepšen systém sestavování webu

Makefile
* Build tak projde, když projde Jekyll (weby, které nefungují nebudou bránit nasazení).
* Na výsledek testů je vhodné se z času na čas podívat manuálně.
* Resolves #257.
=> Výsledek testů webu ignorován

_infografiky/emise/emise-cr-detail.md, _infografiky/emise/emise-cr.md, _infografiky/emise/emise-eu-na-osobu.md, _infografiky/emise/emise-eu-poradi.md, _infografiky/emise/emise-eu.md, _infografiky/emise/emise-vybrane-staty.md
Původní odkaz na zdrojová data byl vytvořen funkcí "bookmark" v toolu Eurostatu. Teorie je, že taková záložka časem vyprší a nebo prostě z jiného důvodu není spolehlivá. Abychom předešli podobnému problému v budoucnu, tento PR nahrazuje detailní odkaz generickým odkazem na dataset env_air_gge.
=> Nahradit rozbitý odkaz datasetu generickým odkazem

_plugins/filter-truncatewords-html.rb
Jeho použití způsobovalo přepsání původního textu a v důsledku nevykreslování stránky se slovníkem.
Oproti původní verzi je změněn jediný znak – problém totiž způsobila záměna `gsub` a `gsub!`.
Fixes #419
=> Oprava filtru truncatewords_html

_layouts/infographic.html
původní text pro mě implikuje, že vidím všechny související infografiky, zatímco jako insider vím, že je zobrazena pouze nějaká podmnožina - upraveným textem chci dát čtenáři tuto skutečnost najevo
na mé konkrétní reformulaci nelpím, jde o princip, který bych rád opravil
=> Popis k souvisejícím infografikám

_layouts/infographic.html
Vypadá to, že dropdown potřebuje element s `display: block`, v tutorialu u Popperu taky mají div.
V [Boostrap dokumentaci](https://getbootstrap.com/docs/4.0/components/dropdowns/#examples) je taky div, potřebuje to `position: relative`, které u inline prvků asi(?) nefunguje.
=> Oprava dropdownu "Zdroje dat" ve Firefoxu

_studie/2020_globalni-zprava-o-elektrine.md
Omylem jsem v popisu studie zaměnil zdroj dat (IEA není EIA...), opravuji. Zdrojem dat ostatních států je americké ministerstvo energetiky (EIA), nikoli Mezinárodní energetická agentura.
=> Oprava zdroje pro Ember

_infografiky/emise/emise-eu-poradi.md
Odkazy na neexistující tabulku odstraněny a místo nich přidána zmínka, kde lze podrobné údaje dohledat.
Resolves #585
=> Odstranění nefunkčních odkazů v doprovodném textu

_includes/footer.html
Patička odkazovala na proměnnou site.repo-url, která ale AFAIK není nikde nastavená, a tak odkazy nefungovaly. Dal jsem tam natvrdo URL repa, to chytřejší řešení s proměnnou nastavenou jinde zatím nevidím jako nutné, když jde jen o dvě použití na stejném místě.
=> Oprava odkazů do repa

Dockerfile, Gemfile, Makefile, README.md, _config.yml, _infografiky/emise/emise-cr.md, _plugins/glyph-replacement.rb, utils/convert-infographic.sh
* Přidán `Dockerfile` pro obraz kontejneru, který by měl být téměř totožný s deploymentem na Travisu.
* Upraveny a rozšíření instrukce pro lokální vývoj v `README.md`.
(Plus drobné úpravy tu a tam, neboť se mi nechce pro každou vytvářet zvláštní PR.)
Nahrazuje #410.
=> Instrukce pro vývoj s kontejnery

_data/news.yml, _infografiky/emise/emise-eu.md, _studie/2018_energetika-cr-bez-uhli.md
Opraveny odkazy na neexistující nebo přesunuté stránky.
Poslední commit, ea551d9, mění odkazy na archivované verze, protože web Glopolisu (dočasně?) nefunguje. (Máme k takovým situacím stanovený postup? Vidím, že i text ke Sternově zprávě se odkazuje na archiv.)
=> Oprava nefunkčních odkazů

_includes/footer.html, assets/_scss/core_design.scss
Layout převeden na flexbox, který si líp poradí s rovnoměrným rozložením prvků.
Před a po:
=> Oprava CSS layoutu v patičce

assets/_scss/index.scss, assets/_scss/tags.scss
Safari na iOS špatně vykresluje barvu `transparent` v přechodech do bílé, viz ilustrace níže. Řešením je změna na „průhlednou bílou”, `rgba(255,255,255,0)`.
=> Oprava průhlednosti gradientů na Safari/iOS

assets/_scss/core_design.scss
Text se zarovnává do bloku pouze u delších souvislých textů, v našem případě v odstavcích a seznamech. Nadpisy apod. zůstavají zarované na levý praporek.
=> Zarovnání do bloku pouze u delších textů

_config.yml, _includes/preview-blocks.html, _layouts/signpost.html, _layouts/tag.html, _rozcestniky/energentika/transformace-energetiky.html
Návrh realizace nového typu obsahu – rozcestníku materiálů, studií, odkazů atd.
Prvním příkladem je rozcestník studí k transformaci české energetiky zpracovaný dle Oldovy tabulky.
K některým studiím budeme mít i doprovodné infografiky. Ty všask ještě čekají na zveřejnění, tudíž je kód pro odkazy na infografiky prozatím zakomentovaný. Odkaz na jedno shrnutí studie (Energynautics) je funkční.
Known issues:
* Na stránce štítku se zobrazuje nadpis "rozcestniky" (s krátkým i).
* Omezená rozšiřitelnost, zobecnitelnost.
Náhled:
=> Rozcestník studií transformace energetiky

assets/js/main.js
Pokud návštěvník přijde na stránku s URL `faktaoklimatu.cz/infografika#nadpis`, přičemž element s ID `nadpis` je uvnitř rozbalovací sekce, měla by se sekce při načtení stránky automaticky rozbalit, aby byl cílový element/nadpis viditelný.
=> Rozbalení rozbalovací sekce při otevření stránky

_includes/_texts/energeticke-scenare/jak-cist.md, _infografiky/energetika/srovnani-energetickych-scenaru-cr.md
Na začátku doprovodného textu by měl být nějaký text, který se dá okamžitě číst, aniž by člověk musel na něco klikat. Rozbalovací
sekce mi na tomto místě nedávají smysl. Navrhuju je proto v úvodním bloku odstranit a nechat je jenom u doplňujících sekcí.
=> Odstranění rozbalovací sekce na začátku textu

_infografiky/emise/potencial-zpusobu-snizeni-emisi.md, _infografiky/energetika/srovnani-energetickych-scenaru-cr.md, _infografiky/opatreni/adaptacni-strategie-cr.md, _infografiky/teploty/cykly-koncentrace-co2.md, _infografiky/teploty/historie-sklenikoveho-efektu.md, _infografiky/teploty/koncentrace-co2.md, _infografiky/teploty/teplota-22000-let.md, _stranky/atlas.md, _studie/2018-scenar-energynautics.md, _studie/2019-scenar-necp.md, _studie/2020-scenar-bloombergnef.md, _studie/2020-scenar-ember.md
Abychom mohli odkazovat na nadpis rozbalovací sekce, musí mít element svoje ID. Kramdown automaticky negeneruje ID pro raw HTML nadpisy, tudíž buď musíme vymyslet ID vlastní, nebo nadpis napsat v Markdown a nechat jej přechroustat Kramdownem. V tomto commitu jsem zvolil druhou cestu kvůli údržbovosti, i když první cesta je možná lepší z hlediska permalink-ovatelnosti.
Closes #712
=> Možnost odkazovat na rozbalovací sekce

assets/js/main.js
Když se cíl odkazu nachází v rozbalovací sekci, sekce se při načtení stránky automaticky otevře, ale ne vždy je cílem nadpis sekce. Někdy je potřeba přeskrolovat až na cíl uvnitř sekce.
=> Skrolování na cíl odkazu v rozbalovací sekci

assets/_scss/core_design.scss
Tento PR opravuje rozbalovací boxíky (obecně, k vidění jsou momentálně na stránce atlasu). Ty byly rozbity úpravou doprovodných textů grafik.
Fixes #741
=> Oprava rozbalovacích boxíků

_infographics/opatreni/svetove-dohody.md
1. změna "kontinentem" -> "územím" (credit goes to _crysman_, že větu vytáhl to newsletteru, a _Ondráš_, že si při revizi textu všiml, že to je blbost - díky!)
2. wikipedie -> Wikipedie
3. drobný překlep odstraněn
=> EU není kontinent a drobné opravy

_data/resources.yml
v Resources bola Cenia prelinkovaná na chmi.cz -> náhrada za link na cenia.cz
=> správny link na Ceniu

_infographics/emise/emise-fosilni-paliva.md
Odstraněn titulek z náhledového boxíku k explaineru emisí z cementu, protože jenom duplikuje nadpis na kartičce.
=> Odstranění nadpisu z náhledového boxíku

_infographics/energetika/srovnani-energetickych-scenaru-cr.md
Přidán redirect z `/srovnani-scenaru` tak, aby fungoval odkaz v grafice.
Fixes #806
=> Přidání redirectu na infografiku srovnání scénářů

_config.local.yml
Závisí na faktaoklimatu/web-core#54.
Příklad použití:
Pythagorova věta $$\oint_\mathcal{C} f(x^2) dx = \frac{a^2 + b^2}{c^2}$$ aproximuje, o kolik se oteplí.
Následující vzorec se zobrazí v _display modu_:
$$\oint_\mathcal{C} f(x^2) dx = \frac{a^2 + b^2}{c^2}$$
Výsledek:
=> Zapnutí podpory pro matematické vzorce

plugins-local/glyph-replacement-czech.rb
In case the `page` object has no `output` property, an error gets logged but execution continues as though nothing has happened. We need to skip processing the document in case an error like this occurs.
Follow-up to faktaoklimatu/web-core#61.
=> Fix crash in glyph replacement plugin

plugins-local/glyph-replacement-czech.rb
Ruby používá pro přeskočení iterace `next`, nikoliv `continue`.
Related: faktaoklimatu/web-core#69
=> Oprava klíčového slova v kódu

_config.local.yml, _pages/aktuality.html, _pages/dekujeme.md, _pages/index.md, assets-local/local.scss
Aktualizován web-core. Interní náhled dostupný na https://cz-fakta-o-klimatu--preview-newsletter-ecomail-nncd42bv.web.app/
=> Newsletter předělán na Ecomail

plugins-local/glyph-replacement-czech.rb
* Použití unicodových glyfů namísto HTML entit.
* Použití look-ahead a look-behind místo explicitního záchytu. To mimochodem opravuje bug, kdy se v _„… letišť a v blízkosti vedení…“_ nahradila mezera za „a“, ale už ne za „v“.
* Použití `\s` místo jednoduché mezery.
Related: faktaoklimatu/web-core#94
=> Vylepšení pluginu pro nahrazování mezer

_config.local.yml
Změna řetězce, kterým se v poznámkách pod čarou odkazuje zpět do textu, na verzi se [selektorem varianty](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)) VS15 (U+FE0E). Tento selektor zajistí, že se šipky nezobrazí jako emoji, což je výchozí chování např. v Safari na iPhonu.
Ilustrace stavu před změnou a po:
=> Potlačení emoji zobrazení šipky

_data/navigation.yml, _pages/index.md, assets-local/local.scss
Aktualizován blok se záložkami dle diskuze s @ondraspribyla (viz #935).
Nyní jsou na titulní stránce prominentně prezentovány materiály k COP26.
Prosím o rychlou kontrolu, @ondraspribyla, aby to mohlo ist von. Preview [dostupné zde](https://cz-fakta-o-klimatu--preview-update-titlepage-e6vz2vus.web.app/).
Pár dalších poznámek:
* Přidán podcast do odkazů v navigační lište.
* Upraveny tlačítka pod titulním nadpisem a v tabech.
=> Aktualizována titulní stránka

Makefile
make 4.3 potřebuje středník za příkazy git (viz https://stackoverflow.com/questions/62561355/permission-error-running-any-git-command-in-makefiles/62562135#comment124673218_62562135). Tento PR to opravuje.
=> Středníky za příkazy git (pro make 4.3)

collections/_topics/emise.md
Navrhuju sjednotit údaje napříč stránkou témat (a napříč webem), že údaje světových emisí vycházejí z EDGARu a údaje pro jednotlivé evropské státy vždy vycházejí z dat eurostatu.
To vede k jisté metodické nedokonalosti, pokud se tyto hodnoty srovnávají mezi sebou, ale rozdíly jsou malé, tak bych to ignoroval. Jednotnost údajů napříč webem je důležitější.
Fixes #1133
=> Sjednocení emisních hodnot

collections/_explainers/bezemisni-energetika-cr-2-technologie.md
Tento commit opravuje drobnou chybu - místo slunečního záření v textu byla výroba (tedy ignorovalo to efektivitu panelu). Toto číslo mělo jen srovnávací účel (ČR : Španělsko)  a nic dalšího na něm nezáviselo, oprava je proto velmi lokální.
=> Oprava chyby v explaineru

collections/_pages/slovnik.html, collections/_pages/zdroje.html
Tento PR uklízí už nepoužívaný parametr seach_id (odstraněný v
https://github.com/faktaoklimatu/web-core/pull/46).
=> Odstranění search_id parametru

collections/_datasets/koncentrace-co2.md
- Oprava některých odkazů na původní data v datasetu koncentrací CO₂ a O₂. Některé původní odkazy už nefungovaly nebo byly přesunuty.
- Doplnění licencí u některých datasetů.
Resolves #1181
=> Oprava odkazů v datasetu koncentrací
