assets/css/main.css

Pridani favicon pred nadpis v hlavicce

---

_infografiky/teploty/koncentrace-co2.md
_infografiky/teploty/koncentrace-co2.pdf
_sekce/teploty.md

Je hotová infografika i text. Další ladění (tzn. úprava weigths jednotlivých grafik, vyladění souvislostí, odkaz na finalizzovaná data, ...) můžeme doplnit za běhu.

Infografika koncentrace co2

---

_infografiky/emise/emise-eu-poradi.md

nesrovnalosti a typos

---

_layouts/infographic.html

Explicitní uvedení slova "licence"

---

AUTHORS.md
_stranky/index.md

Přidáváme stránku AUTHORS.md s kompletním seznamem tvůrců, aktualizujeme seznam tvůrců na hlavní stránce a upravujeme formulaci myšlenky projektu.
Kdyby někoho dráždilo moje jméno na hlavní stránce, klidně ho zatím odstraním. Jen je to takto při jednom.
Fixes #156.

Sekce tvurci

---

assets/css/main.css
assets/js/main.js

Skryti menu pri skrolovani na zarizenich s mensi vyskou plochy

---

.gitignore
README.md

Během rozběhání na wsl ubuntu `bundle install` padalo na nějaké divné chybě, doinstalování zmíněných balíčků pomohlo, nicméně asi půl hodiny jsem to hledal a nevím, jestli bych ten fix našel znovu, tak sdílím.

Ignore IDE files and add info about installation

---

_infografiky/emise/emise-cr-detail.md
_infografiky/emise/emise-cr.md

Ide o prvy kus cistych dat od @jankrcal, viz #77.

Aktualizován odkaz na zpracovná emisní data ČR

---

_data/glossary.yml
_data/news.yml
_includes/navigation.html
_stranky/aktuality.html
_stranky/index.html
assets/css/main.css

Když doplní někdo ty chybějící FIXMEs (už jen 3 tuším) a dva zbývající eventy, tak bych to publikoval. (+ samo někoho na celkové review)

Aktuality skoro ready

---

_stranky/aktuality.html
_studie/2006_sternova-zprava.md
_studie/2019_science-vyjadreni-vedcu.md

* Zkracen popis clanku Science.
* Pridan odkaz na ceske zhrnuti Sternovy zpravy.
* Prihlasovani do newslettru se otevira v novem okne.

Opraveno několik drobností

---

_sekce/emise.md

zatím jen upravena anotace:
1. aby to nevypadalo jako úplný výčet
1. přidán světový kontext
1. přidán odkaz do glossary

Upravena anotace Emisí skleníkových plynů

---

_data/science-czech-signers.yml

Přidány dalši podpisy pod článej ze Science

---

_infografiky/emise/emise-eu-poradi.md
_infografiky/emise/emise-eu.md
_infografiky/emise/emise-vybrane-staty.md

Přesměrovává dataset na novou Google tabulku

Upraveny odkazy na data v .md

---

_infografiky/emise/emise-svet.md

Oddělán workaround na build systém

---

_data/news.yml

přidána chybějící část o emisích světa a zdrojů

---

_infografiky/budoucnost/body-zlomu-1.md
_infografiky/budoucnost/body-zlomu-2.md
_infografiky/budoucnost/body-zlomu-3.md
_sekce/budoucnost.md

...pardon. Vidím, že v Masteri zustal text sekce, ze které jsem to kopíroval... tady je oprava

opraveny text sekce

---

_infografiky/emise/elektrina-cr.md

Opět zapnuto přesměrování pro elektřinu v CR

---

.travis.yml
_infografiky/opatreni/mitigacni-opatreni.md
_sekce/opatreni.md
_studie/2019_IMF-mitigacni-opatreni.md
assets/css/main.css

* Redirect pridany.
* Upraveny styl nadpisov.
* Opravy typografie, konvenvcii projektu, MD suborov a strukturovania textu.

Opravy mitigacne zmeny

---

_infografiky/opatreni/mitigacni-opatreni-mmf.md

Opraven redirect

---

_infografiky/teploty/vyvoj-teplotni-anomalie.md

Tato změna přináší nový pročištěný dataset pro infografiku světové teplotní anomálie. Obsahově je ekvivalentní předchozímu datasetu.

Pročišten dataset pro světovou teplotní anomalii

---

_data/news.yml

týká se #349, doplněny aktuality

Aktualizace aktualit #349

---

_includes/header.html
_layouts/infographic.html

* Anonymizace IP adres návštěvníků.
* Dodržování do-not-track.
* Přidání eventu po rozkliku fullscreen infografiky.
* GA nyní volán přes GTM.

Google analytics vylepšení

---

_infografiky/emise/emise-eu-na-osobu.md
_infografiky/emise/emise-eu.md
_infografiky/emise/emise-vybrane-staty.md

Sjednoceni EU grafik na novou verzi datove sady.

Oprava linku na datovou sadu EU

---

AUTHORS.md

Přidání lidé, co přišli 14. 2. 2020.

Noví lidé na klimatonu do AUTHORS.md

---

_includes/glossary.html
_plugins/filter-truncatewords-html.rb

Dovolil jsem si i zvýšit délku náhledu na 32 slov, přijde mi to pořád v pohodě dlouhé.

Oprava renderování popupů u slovníkových odkazů

---

Gemfile
_infografiky/emise/emise-eu-poradi.md
_infografiky/opatreni/zpoplatneni-emisi-svet.md

Chtěl jsem promazat staré verze souborů s daty, ale zjistil jsem, že jeden byl stále odkazován, opravuji link.
[EDIT - vyreseno, pridal jsem nokogumbo do dependencies, prosim zkontroluj]
@mukrop mimochodem, kdyz jsem si chtel sestavit web lokalne, najednou dostavam pri _make local_:
_Dependency Error: Yikes! It looks like you don't have /mnt/d/projects/fakta-o-klimatu/repo/\_plugins/filter-truncatewords-html.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- nokogumbo' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!_
Predtim jsem dal _bundle install_, protoze mi chybel nejaky dodatecny gem, nainstaloval se v pohode. …

Malé opravy: link na EU emise dataset a typo

---

_infografiky/teploty/mapa-zmeny-teploty.md

Doplněn odkaz na zpracovaná data (NASA).

Přidán odkaz na naše zpracovaná data (Mapa)

---

_infografiky/opatreni/zpoplatneni-emisi-svet.md

- do infografiky `Zpoplatnění emisí: rozšíření ve světě`
- fix #417

Zpoplatnění emisí: přidat odkaz na zpracovaná data

---

_infografiky/opatreni/zpoplatneni-emisi-svet.md

"není doména" -> "není doménou" (Instrumentál)

Zpoplatnění emisí: oprava gramatiky

---

_infografiky/opatreni/zpoplatneni-emisi-svet.md

např: nebo ve slučovacím poměru, chybějící mezera, čárky, skloňování středního rodu atp.

Zpoplatnění emisí: Korektury textu

---

_data/news.yml

- Mapa změn teploty a zpoplatnění emisí
- První účast na větší konferenci (Climate Open Data Expo)
- Souhrnný report větších změn v infografikách

3 nové aktuality

---

.travis.yml

Odstranění git-tools před generování stránky pro gh-pages

---

_infografiky/teploty/teplota-cr-mesice.md

Tato změna vychází ze statistiky úspěšnosti na webu https://www.umimecesky.cz/cteni-s-porozumenim-ipcc/93.

Rozšíření popisku o příklad na konkrétním měsíci.

---

_infografiky/teploty/koncentrace-co2.md

Html tagy nefungují v titulku stránky (zobrazeném na tabu v prohlížeči).

Vrácení unicode subscriptu do názvu stránky

---

CONTRIBUTORS.md
_stranky/index.html

Aktualizace členů týmu

---

_layouts/section.html
_studie/2019_klimaticke-podminky-cr-1.md

Instituce studie zobrazena na titulní stránce

---

_sekce/teploty.md

kozmetická zmena Homo Sapiens -> Homo sapiens

biologická nomenklatúra na titulnej stránke

---

_layouts/dataset.html

Follow-up #481
Díky @katkolouchova za nahlášení.

Oprava dropdownu pro zdroje dat na stránce datasetu

---

_plugins/jekyll-target-blank.rb

Opraveny externí odkazy

---

_studie/2018_energetika-cr-bez-uhli.md

Oprava energynautics

---

_includes/navigation.html
_layouts/dataset.html
_layouts/infographic.html
_stranky/index.md
_stranky/jak-pouzivat.md

Zatím jenom čistě překlopen [text](https://docs.google.com/document/d/1Az2Ye3McsP2VVxlpa_gDdhsyYNV5wDCal_-VNyxvxEc/edit) do Markdownu.
Zkoušel jsem experimentovat s boxem (viz níže), ale nevím, co vypadá dobře, tak zatím bez něj.
Ještě je potřeba dořešit "TODO: fotka Ondráše?"

Přidání stránky "Jak používat naše materiály"

---

_studie/2020_transformace-energetiky-do-2050.md

ešte niekde bude napísaná Česká Republika, asi niekoho zbijem :P

pravopis apod

---

_infografiky/teploty/tropicke-dny-brno.md

Chybělo tam 'v', lehce reformulovano aby nebylo 2x po sobě v

opraven překlep

---

_includes/footer.html
assets/_scss/core_design.scss

* Lepší pozicování a okraje přes flex.
* Větší písmo a ikony pro kontakty.
* Resolves #590.

Upravena patička

---

_stranky/index.md

Responzivní šírky nastaveny identicky jako u ostatních dlaždic na stránce. Na mobilních zařízeních se předchozí verze nezobrazovala optimálně.

Upraven layout dlaždic "Ostatní stránky"

---

_data/tags.yml

hnedouhlenych -> hnedouhelnych
viz #584 .

oprava preklepu v sekci "opatreni"

---

_data/news.yml

doplněny aktuality až do 28.července... jakmile se přimou nejbližší PR, bude třeba doplnit teploty od dob ledových a keelinga
closing #574

update aktualit k 2020-07-28

---

_data/news.yml
_infografiky/teploty/koncentrace-co2.md

- doplněn Keeling a teploty za 22 000 let do aktualit. 
- vyřešeno #473 
Prosím o rev a merge @mukrop

aktuality + doplněný odkaz

---

_infografiky/budoucnost/body-zlomu-1.md
_infografiky/budoucnost/body-zlomu-2.md
_infografiky/budoucnost/body-zlomu-3.md

- oprava překlepu
- doplnění odkazu

upgrade body zlomu

---

_layouts/infographic.html

Upraven text souvisejících infografik

---

Makefile
utils/convert-infographic.sh

* Redukce opakování kódu (DRY)
* Různé drobné Bashové triky

Vylepšení skriptu pro konverzi infografik

---

_layouts/infographic.html

Sekce podkladových dat se již nezobrazovala ve velkém zobrazení, ale pořád ještě ano v mobilním.

Opraveno mobilní zobrazení, když neexistuje dataset

---

_infografiky/opatreni/zpoplatneni-emisi-svet.md

U zpoplatnění emisí jsem upravila překlep v tagu ekonomika.

Úprava překlepu v tagu ekonomika

---

_includes/preview-blocks.html
assets/_scss/index.scss
assets/_scss/tags.scss

Oprava přetékání textu z boxíků

---

_infografiky/emise/potencial-zpusobu-snizeni-emisi.md
_infografiky/opatreni/adaptacni-strategie-cr.md
assets/_scss/core_design.scss

Ukázka v doprovodném textu k infografice adaptačních strategií:

Rozbalovací sekce

---

_stranky/index.md

„Senát“ se jako název instituce píše s velkým počátečním písmenem. Pro jistotu jsem ještě v popisku zdůraznil, že se jedná o Senát Parlamentu České republiky.

Velké písmeno ve slově "Senát"

---

_infografiky/opatreni/adaptacni-strategie-cr.pdf

2020-10-24 K. Kolouchová
- dataset_version_xxxx
- přidána licence
- tečka na konci věty s přísudkem
- velká písmena na začátku popisků
2020-10-26 T. Pšorn
- zapracování připomínek od Romany Brezovské
-- přidání propojení
-- prohození špatně umístěných textů o dopadech
-- přidání zmínky o výzkumu
-- oprava drobných chyb v textu

Update infografiky adaptační strategie

---

CONTRIBUTORS.md
_includes/scripts.html
_stranky/dekujeme.md
assets/_scss/index.scss
assets/js/thankyou.js

- JS to show payment table when params available
- renders table when params `vs` and `amount` are available in the URL

#680 Add: JS to show payment table when params available

---

_studie/2018-scenar-energynautics.md
_studie/2020-scenar-bloombergnef.md

Opravuje několik drobných překlepů.

Proofreading zbývajících stránek k energetice

---

_infografiky/emise/emise-eu-poradi.md
_infografiky/emise/emise-eu.md
_infografiky/emise/potencial-zpusobu-snizeni-emisi.md
_infografiky/teploty/vyvoj-teplotni-anomalie.md

Výskyty "x" pro vyjádření násobků nahrazeny unicodovým glyfem "×"
(U+D7 MULTIPLICATION SIGN).

Mikrotypografie: Unicodový znak pro násobky

---

_stranky/404.md
_studie/1979-charneyho-zprava.md
_studie/2006-sternova-zprava.md
_studie/2018-scenar-energynautics.md
_studie/2019-klimaticke-podminky-cr-1.md
_studie/2019-mitigacni-opatreni-mmf.md
_studie/2019-science-vyjadreni-vedcu.md
_studie/2020-globalni-zprava-o-elektrine.md
_studie/2020-transformace-energetiky-do-2050.md

* Přidána přesměrování ze starých URL studií (s podtržítkem) na nové adresy (se spojovníkem).
* Přidány studie a rešerše do seznamu na stránce 404.

Aktualizace redirectů a stránky 404

---

_studie/2018-scenar-energynautics.pdf

Upravila jsem rozlišení v textu, plus jsem mírně reformulovala pár vět v sekci Model, aby se tam text dobře vešel.
Resolves #710

Úprava chyby v textu

---

_studie/2020-globalni-zprava-o-elektrine.md

text z issue:
Pridat na stranku studie https://faktaoklimatu.cz/studie/2020_globalni-zprava-o-elektrine do metadatoveho panelu obrysove tlacitko na data (https://ember-climate.org/project/data-global-electricity-review/) tak, ako je extra tlacitko na stranke https://faktaoklimatu.cz/studie/2019_science-vyjadreni-vedcu.

Odkazovat ze stránek data studie od EMBER #548

---

.bundle/config
.gitattributes
.gitignore
.travis.yml
Dockerfile
Gemfile.lock
Makefile
_config.yml
_includes/navigation.html
assets/_scss/core_design.scss
assets/js/main.js

* Jemně upraveno prostředí, aby umožňovalo pohodlný vývoj i na Windows.
* Instalace Ruby gemů je nyní lokální (méně problémů se zápisem do systémových cest, přenositelnější, méně interferuje s jinými projekty, lepší cachování, snažší reset prostředí).
* Zafixovány verze závislostí přes společný Gemfile.lock (je to dobrá prax, snižuje problémy ri více vývojářích).
* Přidán banner informulící o lokálním buildu.
* Pokus o opravu chováqní na Apple zařízeních (otestuje @repli2dev ?).
Prosim, mrknite sa na to, ci vam to lokalne funguje dobre, než to dám do upstreamu ostatným :-).

Úpravy vývojářského prostrědí

---

_infografiky/teploty/schema-klimaticke-zmeny.md

Schématická -> schematická, viz [pravidla](https://www.pravidla.cz/hledej/?qr=schematick%FD).

Úprava chyby v nadpisu

---

_data/navigation.yml
_includes/navigation.html

První krok k překladu stránek. Prosím o review.
Vkládání linku pro fundraising je trochu nesystémové, ale zatím to stačí a až bude v budoucnu potřeba, rozšíří se to.

Menu přesunuto do konfigurovatelného YML souboru

---

_infografiky/energetika/srovnani-energetickych-scenaru-cr.md
assets/_scss/infographic.scss

Toto PR dělá drobné dotatečné změny ve velikosti boxů, aby:
- na mobilech byl box poznatelně užší než celá stránka, aby to vypadalo jako box,
- při zvětšování obrazovky velikost boxů příliš neskákala nahorů a dolů,
- dvojitý box byl leckde trochu širší, aby byly grafiky čitelnější.

Poladění velikostí boxů, aby dobře fungovaly ve všech velikostech

---

_data/successes.yml
_stranky/index.md

Carousel uspechu plneny z _data/successes.yml

---

_infografiky/budoucnost/emisni-scenare-pariz.md

Update emisni-scenare-pariz.md - přidány dvě mezery před °C

---

_stranky/o-nas.html

Oprava #755 - podmíněné vytváření odkazů s emailem. Prosím o kontrolu @mukrop.

podmíněné generování odkazů na email

---

_data/news.yml
_datasets/emise-cr.md
_infographics/emise/nejvetsi-emitenti-cr.md
_infographics/emise/nejvetsi-emitenti-cr.pdf

Textově asi jednoduchá grafika... nenapadlo mě nic dalšího co k tomu napsat. Kdyby vás něco napadlo, rád si doplním.

Nejvetsi emitenti

---

_infographics/budoucnost/emisni-scenare-pariz.md
_infographics/opatreni/svetove-dohody.md

Tento PR přidává jeden boxík a dodává k jedné grafice štítek. Oboje inspirováno přípravou newsletter.

Drobne upravy obsahu pro newsletter

---

_data/news.yml
_infographics/emise/emise-fosilni-paliva.md
_infographics/emise/emise-fosilni-paliva.pdf

Zbývající úkoly:
Původní podklady od Global Carbon Budget jsou [zde](https://www.icos-cp.eu/science-and-impact/global-carbon-budget/2020).
Resolves  #762

Světové emise CO2 z fosilních paliv a výroby cementu

---

_infographics/emise/emise-fosilni-paliva.md

Ještě je potřeba upravit konfiguraci preview boxů, aby umožňovala přidat i explainery.

Přidání náhledu explaineru k výrobě cementu

---

_data/lang.yml
_explainers/emise-dychani.md
_explainers/emise-vyroba-cementu.md
_explainers/evropska-zelena-dohoda.md

Dodává info o licenci a autorech do existujících explainerů.
Fixes: #778

Licence pro explainery

---

_infographics/budoucnost/emisni-scenare-pariz.md
_infographics/emise/emise-fosilni-paliva.md

Došlo ke spojení [tohoto](https://docs.google.com/spreadsheets/d/19PiqYV6FkttzrNcjkbTQmphzxgydtTc1MB6nDZpybj0/edit?usp=sharing) a [tohoto](https://docs.google.com/spreadsheets/d/1livivZOC7ha7UkAqiMJtvt1AnMRUq-aNsta8KKgxQ44/edit?usp=sharing) datasetu do jednoho.
Prosím, Jeňo, o check.

Spojení datasetů + aktualizace dat o rok 2019

---

_data/news.yml

+ rozšíření na Slovensko
+ explainery
* opravena zmizelá aktualita Mezinárodní klimatické dohody
* několik oprav drobných gramatických chyb celkově
nahrazuje https://github.com/faktaoklimatu/web-cz/pull/779, který tímto zavírám

nové aktuality + opravy chyb

---

_data/lang.yml
_pages/aktuality.html
_pages/slovnik.html
_pages/zdroje.html

Tento PR upravuje pár detailů v českém webu pro nasazení vyhledávání.

Vyhledávání

---

_data/news.yml
_infographics/emise/emise-fosilni-paliva.md
_pages/atlas.md

* Nahrazení CO2 → CO₂.
* Mezery a čárky.

Oprava typografických drobností

---

_infographics/teploty/cykly-koncentrace-co2.md
_infographics/teploty/koncentrace-co2.md
_infographics/teploty/schema-klimaticke-zmeny.md

Tento PR přidává prolinkování grafik mezi sebou. Obecně by bylo potřeba projít a prolinkovat více grafik a postupně je napojovat s explainery, ale bude to asi iterativní práce. Tak dávám k PR.

Prolinkovani grafik

---

_pages/atlas.md
_pages/jak-pouzivat.md
firebase.json

Tento PR:
- nasazuje nové změny ve web-core,
- přidává do search.json dvě další speciální stránky,
- přidává connect-src self do Content-Security-Policy-Report-Only (kvůli search.json)

Opravy vyhledávání

---

firebase.json

Snizuje zavislost webu na vice CDN sluzbach, ktere nahrazuje za jediny - cloudflare.com

Zjednoduseni CSP - cloudflare.com

---

plugins-local/glyph-replacement-czech.rb

Este chcem oznacit @Jirka-tisnov, pretoze je autor nametu a pripadna diskusia tu sa ho moze tykat.

Rozšířen filter na automatické pevné mezery

---

_data/news.yml

- aktualita o možnosti vyhledávání na webu
- drobné úpravy textu (kosmetika)

přidáno vyhledávání, drobné úpravy

---

_explainers/emise-dychani.md

drobné doplnění poznámky, mělo by být bez problémů...

doplnění poznámky o dýchání rostlin

---

_studies/2020-reserse-transformace-energetiky.md

Přidána aktualizovaná studie Deloitte pro Svaz moderní energetiky (prosinec 2020) a studie teplárenství z FEL ČVUT (únor 2021).
Closes #814
Closes #815

Aktualizace rešerše studií transformace energetiky

---

Makefile

Přidán cíl deploy-production in do lokaliovaného repa.

Opraven build

---

_data/news.yml

na čitelnější verzi z facebooku/newsletteru (by @Jirka)

reformulace popisu explainerů

---

_infographics/teploty/teplota-22000-let.md

Doplněn odkaz na nejnovější databázi paleoklimatických dat

---

_studies/2021-reserse-zavazky-statu.md

Závisí na faktaoklimatu/web-core#60.

Rešerše: Emisní závazky států

---

_pages/index.md

https://github.com/faktaoklimatu/web-core/issues/16
- Oprava `aria-labelledby` s neexistujicim ID.
- Role pro accordion header

#16: fix invalidniho html.

---

README.md

- syntax err u hyperlinku fixed (přebývala závorka)
- přidán hyperlink na darujme
- opraveny některé typos a chyby
- přidána nějaká slova do popisu o projektu
- +kurzíva

chybný hyperlink + drobné úpravy

---

_data/lang.yml
_pages/gdpr.md

Přidány Zásady zpracování osobních údajů

---

_pages/gdpr.md

změny v textaci (přidání uděleného souhlasu)

---

_data/glossary.yml

Přidání dvou malých hesel do slovníčku (časem by se hodilo přidat více hesel, prolinkovat hesla vzájemně a přidat link z NDC na naši rešerši národních závazků - ale není to nic, co by mělo blokovat tuto malou úpravu - proto nechávám pouze k technickému posouzení a pouze pro info taguju @Filip-Kessner )

Přidány hesla Greenwashing a NDCs

---

_infographics/teploty/koncentrace-co2.md

Drobná změna, asi ready to merge. Ale nechávám na vás, jednak abyste o tom věděli, a abyste případně doplnili příznak pro propsání do slovenských stránek...

Doplněn odkaz na článek - koncentrace CO2 za poslendích 66 milionů let

---

_config.local.yml
_infographics/energetika/srovnani-energetickych-scenaru-cr.md

Vid https://github.com/faktaoklimatu/web-core/pull/80

Malé vylepšení HTML, přidán Facebook a LinkedIn

---

_datasets/koncentrace-co2.md
_datasets/teplota-cr.md
_infographics/budoucnost/body-zlomu-1.md
_infographics/budoucnost/body-zlomu-2.md
_infographics/budoucnost/body-zlomu-3.md
_infographics/opatreni/adaptacni-strategie-cr.md
_infographics/opatreni/mitigacni-opatreni-mmf.md
_infographics/opatreni/zpoplatneni-emisi-svet.md
_infographics/teploty/mapa-zmeny-teploty.md
_infographics/teploty/souvislost-koncentrace-oteplovani.md
_infographics/teploty/teplota-22000-let.md
_infographics/teploty/teplota-cr-mesice.md
_infographics/teploty/teplota-cr.md
_infographics/teploty/trend-teplot-cr.md

Striktně technicky YAML nepovoluje tabulátory. Navíc jednotné odsazování mezerami zjednodušuje strojové zpracování (`grep` apod.).

Konverze tabulátorů na mezery v preambulích

---

_studies/2021-reserse-zavazky-statu.md

Vytvaram PR za Fila, aby pripadne problemy a nezrovnalosti dali diskutovat priamo pri zmenach kodu,
* doplněna UK, lepší zdroje a data aktualizací zdrojů

Vylepšení rešerše zavazků států

---

_data/tags.yml
_explainers/vymirani-koralovych-utesu.md
_infographics/budoucnost/body-zlomu-1.md

Při přidání rešerše lesů ČR jsme zavedli novou kategorii příroda (ekosystémy, biodiverzita, krajina). Doplňuji tento tag k relevantnímu stávajícímu obsahu.
@mukrop prosím o review + merge, díky.

Doplnění tagu příroda

---

_data/glossary.yml
_infographics/emise/potencial-zpusobu-snizeni-emisi.md

- nový pojem ve slovníku
- přidán odkaz z potenciálu emisí
- slovník re-seřazen dle abecedy 
"definice" rozhodně není finální, je to výkop pro případnou reformulaci - @ondraspribyla ?

pojem sekvestrace

---

_studies/2020-scenar-mckinsey.pdf

Aktualizace textu u investic v grafice McKinsey

---

_infographics/energetika/potencial-vetrne-energie-cr.md

rok jsem doplnil dle datasetu, tak snad je to OK

doplněn chybějící rok

---

_pages/slovnik.html

[Preview](https://cz-fakta-o-klimatu--preview-slovnik-obsah-enyv5e6p.web.app)

Přidání obsahu do slovníku pojmů

---

_infographics/budoucnost/uhlikovy-rozpocet-cr.md

Korekce Uhlíkový rozpočet ČR

---

_infographics/opatreni/nizkouhlikova-spolecnost.md

https://faktaoklimatu.slack.com/archives/C01C6UQBS2X/p1630658720013000?thread_ts=1630614489.011600&cid=C01C6UQBS2X

pridan infobox na potencial

---

_data/lang.yml

Adding czech translation for fancybox.
See faktaoklimatu/web-core#105

Adding translation for fancybox.

---

_infographics/priroda/lesnatost-kraje.md
_infographics/priroda/lesnatost-plo.md

Opravey názvy stránek dle názvů v infografikách

---

_data/lang.yml

Related: faktaoklimatu/web-core#139

Aktualizace lokalizačních řetězců

---

_data/lang.yml

Po merge ve `web-core` bude potřeba upravit commit, aby smroval na nový `master` ve `web-core`.
Preview na https://cz-fakta-o-klimatu--preview-feed-5-f3tofcca.web.app

Přidán Atom feed

---

_datasets/emise-cr.md

Opraven link v datasete

---

_explainers/pozice-akteru-cop.md
_explainers/uhlikova-neutralita.md

Preview upravených stránok:
* https://cz-fakta-o-klimatu--preview-data-stale-warning-zujrwbm3.web.app/explainery/pozice-akteru-cop
* https://cz-fakta-o-klimatu--preview-data-stale-warning-zujrwbm3.web.app/explainery/uhlikova-neutralita
Resolves #952.

Přidáno varování na starší data

---

_infographics/energetika/elektrina-sr.md
_infographics/energetika/elektrina-sr.pdf

Přidává Sankeyho diagram výroby elektřiny na Slovensku.
Chybí:
Revize datasetu, apod už se dělala pro slovenský web, tak to nemusíme znovu.

Elektřina SR

---

_infographics/energetika/elektrina-na-osobu-svet.md

Úprava jednotek

---

_studies/2020-globalni-zprava-o-elektrine.md

Tento PR dodává odkaz na výpočet a opravuje hodnotu pro uhlíkovou intenzitu českého elektřiny.

Oprava vypoctu pro Cesko v globalni zprave o elektrine

---

_infographics/opatreni/fit-for-55-opatreni.md
_infographics/opatreni/fit-for-55-opatreni.pdf
_infographics/opatreni/fit-for-55.md
_infographics/opatreni/fit-for-55.pdf

Preview zde: https://cz-fakta-o-klimatu--preview-fit-for-55-sb60zvrj.web.app/infografiky/fit-for-55
a zde: https://cz-fakta-o-klimatu--preview-fit-for-55-sb60zvrj.web.app/infografiky/fit-for-55-opatreni

Fit for 55

---

_pages/o-nas.html
assets-local/local.scss

Inline styl přesunut do lokálního CSS

---

includes-local/object-stats.html

Opraven neexistující liquid filter

---

_infographics/emise/emise-cr-vyvoj.md
_infographics/emise/emise-cr-vyvoj.pdf
_infographics/emise/emise-eu-vyvoj.md
_infographics/emise/emise-eu-vyvoj.pdf

Vývoj emisí EU

---

_infographics/energetika/potencial-solarni-energie-cr-strechy.md
_infographics/energetika/potencial-vetrne-energie-cr.md
_pages/index.md

Jde o nahrazení COPu aktuálně diskutovaným balíčkem F55. Prosím o technické review, případně reformulace v doprovodném textu.
(Plus jsem upravila váhu u dvou infografik, aby infografiky s vývojem emisí byly v sekci energetika vedle sebe.)
Resolves #1006

Update sekce Aktuálně na titulní straně

---

_pages/index.md

Úprava odkazu pod tlačítkem na podcast

---

_infographics/opatreni/fit-for-55-opatreni.md
_infographics/opatreni/fit-for-55.md

Resolves #1027
Úpravu grafiky zatím dělat nebudeme.

Update textu k FF55 o nové návrhy a další experty

---

_studies/2020-scenar-ember.md

Aktualizace linku u shrnutí studie Ember

---

_data/organization-members.yml

Preview [stránky O nás](https://cz-fakta-o-klimatu--preview-emails-vqdr38mn.web.app/o-nas) s novými emailami.

Přidány existující emaily na členy

---

_topics/energetika.md

Přidává zapomenutý příznak sitemap: false.

Skrýt téma energetiky

---

collections/_infographics/energetika/potencial-solarni-energie-cr-strechy.pdf
collections/_infographics/energetika/potencial-vetrne-energie-cr.md
collections/_infographics/energetika/potencial-vetrne-energie-cr.pdf

Zapracovala jsem všechny poznámky z issue, včetně těch do doprovodného textu.
Zároveň jsem při té příležitosti upravila sklon u fasádní FVE z 0 na 90°.
Resolves #1050

Update větrného potenciálu podle poznámek

---

.gitmodules
Makefile
_config.local.yml
_data/lang.yml
collections/_episodes
collections/_explainers/cena-elektriny-na-trhu.md
collections/_topics/energetika.md

Tento PR přidává podcasty jako objekt na webu:
- přidává web podcastu jako submodul,
- přidává epozidy jako kolekci, která se nerenderuje (obsah pomocí symlinku),
- přidává ukázkové použití epizod na stránce tématu energetika.

Přidání podcastů jako objektu na webu

---

_config.local.yml

Tento PR jen aktualizuje web-core, kde byla opravena chyba v generování obrázků epizod.

Oprava generování obrázků epizod

---

collections/_studies/2020-reserse-transformace-energetiky.md
collections/_studies/2021-reserse-lesy-cr.md
collections/_studies/2021-reserse-zavazky-statu.md

Tento PR sjednocuje design karet produktů. Více popisu v https://github.com/faktaoklimatu/web-core/pull/175.
V českém webu odstraňuje prefixy "Rešerše" z názvu rešerší. Budou nově přidané automaticky.

Sjednocení designu kart produktů

---

collections/_topics/emise.md
collections/_topics/energetika.md
collections/_topics/klimaticka-zmena.md
includes-local/preview-featured-blocks.html

Tento PR přidává komentované boxy do 3 sekcí "V kostce". Další sekce zpracují následující PRs.
Kromě toho tento PR dělá jednu drobnou technickou změnu související s úklidem includes (viz změny https://github.com/faktaoklimatu/web-core/pull/177).
PR taky aktualizuje web-core na aktuální master, což zahrnuje také https://github.com/faktaoklimatu/web-core/pull/178, který zjednodušuje preview boxy epizod podcastu.

Implementace a použití komentovaných boxů pro 3 sekce 'V kostce'

---

collections/_topics/ekonomika.md
collections/_topics/emise.md
collections/_topics/energetika.md
collections/_topics/klimaticka-zmena.md

Tento PR přidává do stránek témat doposud chybějící obsah (jak ho odhalily nové automatické testy).

Přidání chybějícího obsahu

---

_data/glossary.yml
_data/lang.yml
collections/_topics/dohody-legislativa.md
collections/_topics/ekonomika.md
collections/_topics/emise.md
collections/_topics/energetika.md
collections/_topics/klimaticka-zmena.md
collections/_topics/krajina.md

Tento PR sjednocuje intro texty u stránek témat a dodělává komentované boxy pro zbývající 3 témata.
Záměr je následující:
- **v intro textu** dát krátký, spíš méně technický a méně hutný úvod, který téma zarámuje a dá do kontextu (moje pracovní otázky, na které tam chci odpovídat jsou "Co to v kontextu změny klimatu je a proč je to důležité")
- **V kostce** dát o něco techničtější deep dive do těch nejpodstatnějších pojmů, dat, informací.
V tématech krajina a dohody-legislativa také tento PR drobně upravuje pořadí sekcí a umístění několika otázek. 
Kromě toho PR upravuje jedno slovníkové heslo použité na stránkách témat (nahrazuje nesmyslný text odkazu ghgprotocol.com něčím stravitelnějším).
Tento PR zatím neaktualizuje myšlenkové mapy, ty budou později nahrazeny ikonkami / ilustracemi.

Úpravy intro textů na stránkách témat a další úpravy 'V kostce'

---

_data/lang.yml
collections/_topics/ekonomika.md
collections/_topics/emise.md
collections/_topics/energetika.md
collections/_topics/klimaticka-zmena.md

Tento PR přidává sekundární navigační lištu pro stránky témat.
Aby se sekce na stránkách témat vešly na jeden řádek, tento PR dále:
- definuje kratší názvy sekcí,
- tu a tam upravuje názvy sekcí, aby více ladily se zkrácenými názvy.

Navigační lišta pro stránky témat

---

collections/_explainers/zpravy-ipcc.md

@katkolouchova Aktualizoval jsem zbývající věci v explaineru IPCC a tímto je, myslím, hotovo :-)

Aktualizace explaineru IPCC

---

_data/lang.yml

See faktaoklimatu/web-core#184

Lokalizace tlačítka na stránce tagu

---

collections/_topics/dohody-legislativa.md
collections/_topics/ekonomika.md
collections/_topics/emise.md
collections/_topics/energetika.md
collections/_topics/klimaticka-zmena.md
collections/_topics/krajina.md

@jankrcal Změnil jsem pár drobností u Klimatické změny. U toho zvýšení hladin mám trochu problém s tím, že tam (na rozdíl od oteplení) není řečeno, k čemu se vztahuje to zvýšení (je to oproti dnešku nebo jakému datu?).

Editace dashboardů a V kostce

---

collections/_pages/index.md

Tento PR přináší změny z https://github.com/faktaoklimatu/web-core/pull/186 do českého webu.
K tomu jsou potřeba různé drobné úpravy v html kódu index.md.
Preview: https://cz-fakta-o-klimatu--preview-tuning-mobile-4aw3334u.web.app

Zlepšení layoutu pro mobily na hlavní stránce a stránkách témat

---

_data/lang.yml
collections/_pages/index.md
includes-local/preview-featured-blocks.html

Tento PR nasazuje rozbalovátka (https://github.com/faktaoklimatu/web-core/pull/185) na český web do
- stránek témat (kromě "V kostce"),
- na hlavní stránku do sekce "Aktuálně".
Preview: https://cz-fakta-o-klimatu--preview-boxes-more-rvzgnvw2.web.app/tema/emise

Nasazení rozbalovátek do bloků s obsahovými boxy

---

collections/_pages/404.md
collections/_pages/index.md

Tento PR přidává další drobná využití rozbalitelných bloků materiálů.

Další použití expanderů

---

collections/_topics/dohody-legislativa.md
collections/_topics/emise.md
collections/_topics/klimaticka-zmena.md

Tento PR dělá drobné finální úpravy na stránkách témat:
- rozděluje QAs na stránce `emise` po sekcích
- opravuje drobné technické chyby na stránce `dohody-legislativa`
- zjednodušuje neutrality na dashboardu `dohody-legislativa` - silnější klimatickou neutralitu EU nahrazuje srozumitelnější uhlíkovou
- dělá další úpravy tématu `změna-klimatu`

[Stránky témat] Obsahové ladění

---

_data/organization-members.yml

Po vzoru aktualizace vašich jsem zdrůraznil svoji expertní složku.

Aktualizován Martinův medailonik

---

collections/_topics/dohody-legislativa.md
collections/_topics/ekonomika.md
collections/_topics/emise.md
collections/_topics/energetika.md
collections/_topics/krajina-ekosystemy.md

související issue: https://github.com/faktaoklimatu/web-cz/issues/1100

jazykové úpravy, korektura stránek témat

---

_data/lang.yml

Related: faktaoklimatu/web-core#196

Lokalizace řetězce v patičce

---

_data/lang.yml
collections/_pages/index.md

Tento PR zapracovává drobný feedback k hlavní stránce, navigaci, patičce.
Konkrétně:
- přidává mobile only tlačítka "Podpořte nás" mezi intro tlačítka a do patičky,
- ruší zalomení v tagline na mobilu ("Veřejně dostupné infografiky..."
- nahrazuje tab "Aktuálně: ... " za "Vybíráme: ..." pro větší jasnost v kontrastu s "Nejnovější"
- zmenšuje spacing mezi tématy, kterým se věnujeme na mobilu
- větší font do (rozbaleného) navigačního menu na mobilu
https://cz-fakta-o-klimatu--preview-drobny-feedback-g3smin7r.web.app
@katkolouchova:
- nechápu Tvoji připomínku: "Já bych v mobilní verzi klidně dala sekce O naší práci a Ocenění stejně velkým fontem jako zbylé sekce (tedy menším)." Zdá se mi, že má stejně velký font jako zbylé sekce, např. "Oblasti, kterým se věnujeme", tedy je to H2.display-2. …

Zapracování drobného feedbacku

---

collections/_pages/index.md

Tento PR mění aktuální modrou sekci na hlavní stránce na obsah určený k Týdnu pro klima 2022.
https://cz-fakta-o-klimatu--preview-tyden-pro-klima-m1a3i21v.web.app

Změna sekce "Vybíráme" na Týden pro klima

---

collections/_studies/2019-scenar-necp.md

Tabulátory rozbíjí některé parsery YAMLu.

Odstranění tabulátoru z YAMLU

---

collections/_studies/2022-reserse-ccs.md
collections/_topics/emise.md

[Preview zde](https://cz-fakta-o-klimatu--preview-reserse-ccs-fuqhxflm.web.app/studie/2022-reserse-ccs)

Rešerše CCS

---

collections/_studies/2021-reserse-zavazky-statu.md

Drobné aktualizace a úprava nefunkčních odkazů (registr NDCs změnil strukturu, přidala jsem proto odkazy přímo na pdf se závazky jednotlivých států).
Preview: https://cz-fakta-o-klimatu--preview-reserse-zavazku-update-3bpp1wfo.web.app

Update rešerše emisních závazků

---

_config.local.yml
_data/navigation.yml
includes-local/fr-vanoce-2022.html

Tento PR přidává banner k aktuální vánoční kampani.
Preview: https://cz-fakta-o-klimatu--preview-campaign-banner-62xp0iw3.web.app

Banner vánoční kampaň

---

collections/_pages/atlas.md

Tento PR používá include na rozbalovací boxy místo předchozího html-only řešení. Také nasazuje tento include na QA na stránce témat.
Předchozí kód byl použit výhradně na stránce Atlasu, takže tento PR sjednocuje všechny rozbalovací boxy na webu (vizuálně totožné řešení je použito také pro rozbalování seznamu obsahových boxů).
Preview: https://cz-fakta-o-klimatu--preview-expandable-atlas-b2ns1jmw.web.app/atlas a např. https://cz-fakta-o-klimatu--preview-expandable-atlas-b2ns1jmw.web.app/temata/klimaticka-zmena

Sjednocení rozbalovacích boxů na stránce Atlas

---

collections/_datasets/emise-cr.md
collections/_infographics/emise/emise-sr.md

Tento PR aktualizuje odkazy na tabulku emisí podle ETS
(v Google tabulkách datasetů jsem to už opravil in-place).

Aktualizace odkazů na data z ETS

---

collections/_pages/index.md

Oprava drobného bugu z #1127.
[Preview](https://cz-fakta-o-klimatu--preview-skryti-darujme-mobil-xtvkpx4q.web.app)

Skrytí darujme in na mobilu

---

includes-local/fr-vanoce-2022.html

Tento PR znovu vrací do banneru ke FR kampani větu "Chcete náš designový plakát nebo aktualizovaný Atlas klimatické změny?".
Od teď je tato verze časově neohraničená, na konci kampaně potřebujeme banner prostě smazat.
Preview: https://cz-fakta-o-klimatu--preview-fix-campaign-q99us6vs.web.app

Vrácení detailů ke kampani

---

collections/_explainers/vliv-klimatu-na-extremy-prirucka.md

Tento PR přidává odkazy na oficiální PDF verzi příručky a přidává jasnou atribuci iniciativě World Weather Attribution ;)
Preview: https://cz-fakta-o-klimatu--preview-odkaz-prirucka-4hq9ho6v.web.app/explainery/vliv-klimatu-na-extremy-prirucka

Přidání odkazů na příručku a WWA

---

_config.local.yml
_data/lang.yml
collections/_pages/o-nas.html

Tento PR přidává fakturační údaje do stránky o nás a také přidává odkaz na tyto údaje do patičky.
Preview: https://cz-fakta-o-klimatu--preview-fakturacni-udaje-jo7i3zfq.web.app/o-nas#fakturacni-udaje

Přidání fakturačních údajů

---

_config.local.yml
_data/navigation.yml
collections/_pages/index.md

Tento PR odstraňuje banner k vánoční FR kampani. Veškerý kód zůstává, tedy není problém časem nasadit podobný banner.
Preview: https://cz-fakta-o-klimatu--preview-konec-vanocniho-fr-banneru-a0mckxs2.web.app

Odstranění FR banneru

---

_data/organization-members.yml

Adresa by na konci neměla mít mezeru.

Oprava e-mailových adres

---

collections/_pages/index.md

@jankrcal Uprav podle potřeby :)

Aktualizace sekce Vybíráme

---

collections/_pages/atlas.md

Prosím o review a klidně rovnou o merge @jankrcal

Přidání pdf aktualizovaného Atlasu

---

collections/_studies/2021-reserse-zavazky-statu.md

Úprava nefunknčného odkazu na vlajku UK

Reserse emisini zavazky statu

---

collections/_explainers/technologie-dekarbonizace-prumyslu.md

oprava datum

---

_data/lang.yml

Tento PR přesouvá názvy regionů do lokálního lang.yml.

Lokalizace regionů na stránce témat

---

collections/_pages/atlas-obchod.md
collections/_pages/atlas.md
collections/_pages/jak-pouzivat.md
collections/_pages/modelovani-energeticke-transformace.md
collections/_pages/slovnik.html
collections/_pages/zdroje.html

Tento commit současně reflektuje změny ve web-core a upravuje všechny speciální stránky ve vyhledávacím indexu.
Podstránka "atlas-obchod" vědomě není přidaná do indexu, protože vypadá příliš podobně jako "atlas" a tak by to bylo matoucí.

Náhledový obrázek pro stránky atlasu

---

collections/_studies/2021-reserse-zavazky-statu.md

Update Emisních závazků - NDCs, CATs

---

collections/_pages/atlas.md

Tento PR přidává novou URL adresu `/atlas-klimaticke-zmeny-materialy`, dedikovanou na QR kód k Atlasu klimatické změny.
V tuto chvíli je tam jen redirect na současnou stránku `/atlas`.
Preview: https://cz-fakta-o-klimatu--preview-permalink-atlas-plk2jyee.web.app/atlas-klimaticke-zmeny-materialy

Permalink pro QR kód na Atlasu

---

collections/_pages/index.md

Kromě toho přidává odkazy (odkaz na AFO neexistuje) a upravuje pořadí na
most-recent-first.
Preview: https://cz-fakta-o-klimatu--preview-cena-vavrouska-bhdt0zek.web.app

Přidání ceny Josefa Vavrouška

---

collections/_studies/2023-reserse-soil-carbon.md
collections/_topics/krajina-ekosystemy.md

[:point_right: Preview zde :point_left:](https://cz-fakta-o-klimatu--preview-reserse-soil-carbon-dpx61gom.web.app/studie/2023-reserse-soil-carbon)

Rešerše: Soil carbon

---

collections/_infographics/energetika/elektrina-mix-eu.md

diky @Jirka-tisnov za náhodné zmienenie tejto IG v Slacku :)))

oprava názvu IG

---

README.md

Prosím o kontrolu terminológie a češtiny.

Přidání instrukcí a tipů pro řešení technických  problémů

---

collections/_studies/2023-reserse-extremy.md

nahození poznámek k tabulce

---

_data/organization-members.yml
collections/_explainers/klimaticke-zavazky-cr.md

[**PREVIEW**](https://cz-fakta-o-klimatu--preview-o-nas-stazistky-8elr6eco.web.app/o-nas)
Přidání Elišky a Kristýny a řazení podle abecedy v sekci Dále nám pomáhají.

Aktualizace týmu na stránce O nás

---

.gitignore

Tento PR nastavuje, aby se ignorovaly soubory .DS_Store, které automaticky vytváří Mac Finder.

Ignorovat .DS_Store soubory na Macu

---

collections/_studies/2023-reserse-extremy.md

Podle [zpráv CBC](https://www.cbc.ca/news/climate/wildfire-season-2023-wrap-1.6999005) shořelo za sezónu 2023 více než 18 tisíc hektarů půdy.

Aktualizace rozsahu shořené půdy

---

collections/_topics/krajina-ekosystemy.md

Aby se správně zobrazil boxík série na stránce explaineru, je třeba vytvořit sérii a její popisek na příslušné stránce tématu.
Previews:
- [Explainer 1](https://cz-fakta-o-klimatu--preview-offsety-serie-yuysxr7t.web.app/explainery/uhlikove-offsety)
- [Explainer 2](https://cz-fakta-o-klimatu--preview-offsety-serie-yuysxr7t.web.app/explainery/uhlikove-offsety-problemy)
- [Stránka tématu](https://cz-fakta-o-klimatu--preview-offsety-serie-yuysxr7t.web.app/temata/krajina-ekosystemy#serie-uhlikove-offsety)

Přidání série offsetů na stránku témat

---

collections/_explainers/uhlikove-offsety.md

Na základě připomínky expertky

Uhlikove offsety oprava CO2eq.md

---

collections/_infographics/energetika/uzemni-stopa-oze.pdf

Úprava výplně plochy větrných parků.

Úprava zobrazení plochy větrných parků

---

collections/_explainers/elektrifikace-dopravy.md

- Přidání alt textu.
- Opravy čísel v úvodu textu pro konzistenci s pozdějším textem.
- Lehká úprava formulace.

Drobné úpravy v explaineru elektrifikace dopravy

---

collections/_pages/index.md

Čaká na merge #1303 aktulizace teplotních infografik.

Aktualizace úvodní stránky (Rekordní rok 2023)

---

collections/_pages/index.md

Přetextování tlačítka na "@faktaoklimatu" pro lepší čitelnost.

Úprava odkazu na X

---

collections/_pages/atlas.md

[Preview](https://cz-fakta-o-klimatu--preview-atlasklimatickezmeny-077jtpm9.web.app/atlas)

Přidání otázke k Atlasu klimatické změny

---

collections/_explainers/emisni-povolenky-ets-2.md
collections/_topics/dohody-legislativa.md
collections/_topics/ekonomika.md
collections/_topics/emise.md

Preview: https://cz-fakta-o-klimatu--preview-skryt-ets2-ekhj2l7z.web.app/

Dočasné skrytí explaineru EU ETS 2

---

_data/organization-members.yml

- Refresh popisku u Milana.
- Aktualizace příjmení u Matěje.

Aktualizace O nás

---

collections/_explainers/emisni-povolenky-ets-2.md
collections/_topics/dohody-legislativa.md
collections/_topics/ekonomika.md
collections/_topics/emise.md

Toto je v principu revert PR #1323.
Preview: https://cz-fakta-o-klimatu--preview-zverejneni-ets2-10wr0o8u.web.app/explainery/emisni-povolenky-ets-2

Zveřejnění explaineru ETS2

---

collections/_studies/2020-reserse-transformace-energetiky.md

[Preview](https://cz-fakta-o-klimatu--preview-aktualizace-reserse-studii-bdf0vzcy.web.app/studie/2020-reserse-transformace-energetiky)

Aktualizace rešerše studií k transformaci energetiky

---

_data/glossary.yml

[Preview](https://cz-fakta-o-klimatu--preview-slovnik-klqmseco.web.app/slovnik)

Aktualizace slovníkových hesel

---

assets-local/local.scss
collections/_explainers/emise-doprava.md
collections/_explainers/zpravy-ipcc.md
collections/_infographics/energetika/uzemni-stopa-oze.md

[Preview](https://cz-fakta-o-klimatu--preview-refresh-tabulek-yoyycssj.web.app)
Hlavní dotčené tabulky:
- [emise z dopravy](https://cz-fakta-o-klimatu--preview-refresh-tabulek-yoyycssj.web.app/explainery/emise-doprava)
- [územní stopa OZE](https://cz-fakta-o-klimatu--preview-refresh-tabulek-yoyycssj.web.app/infografiky/uzemni-stopa-oze)

Vizuální refresh tabulek

---

collections/_pages/atlassfzp.md

[Preview](https://cz-fakta-o-klimatu--preview-atlas-update-4rzpu5zc.web.app/atlassfzp)

Stránka publicity pro Atlas dekarbonizace

---

collections/_explainers/emise-doprava.md

Pro jistotu je lepší uvést jak zdroj dat, tak i to, že grafy jsme vytvořili my. Navíc linkujeme přímo na explainer, kde se grafika objevuje.

Oprava uvedení zdrojů

---

collections/_pages/atlassfzp.md

[Preview](https://cz-fakta-o-klimatu--preview-sfzp-stranka-loga-tggseunu.web.app/atlassfzp)

Přidání log MŽP a SFŽP na stránku atlasu

---

collections/_topics/emise.md

Tato úprava ja založena na připomínce z ÚFA AV.

Přidání slůvka "antropogenní" do úvodu sekce Emise

---

collections/_pages/gdpr.md

Anicka Mackova -> Martin Ukrop

Aktualizace kontaktni osoby GDPR

---

_config.local.yml
assets-local/js/dotaznik.js

Preview: https://cz-fakta-o-klimatu--preview-dotaznik-qg00bznx.web.app
Kód je tam nahraný, potřebuju ale navést, kam umístit spouštění toho kódu, aby se v ideálním případě spouštěl jen na českém webu. Mám za to, že kdybych jej vložil do web-core (třeba do headeru), tak se spustí i na anglickém a slovenském webu, nedokázal jsem zjistit zda je v tom šablonovacím jekyll syntaxi možné přistoupit k proměnné na jaké jazykové variantě webu jsem a podle toho skript zobrazit nebo ne.
Umístit buď do hlavičky: <script src="/assets-local/js/dotaznik.js" defer></script>
nebo na konec stránky před /body: <script src="/assets-local/js/dotaznik.js"></script>
Jediné co mě napadá je vložit do assets-local slovenské a anglické verze prázdný  soubor dotaznik.js, aby se sice načetl, ale nespustil, ale to …

Přidán kód pro dotazník.

---

collections/_infographics/teploty/mapa-zmeny-teploty.md

Tento PR opravuje hodnotu oteplení, která se nevtahuje vůči preindustriálu (1,2 stupně), ale vůči roku 1961 (1 stupeň).

Oprava hodnoty oteplení oproti roku 1961

---

collections/_pages/o-nas.html

[Preview](https://cz-fakta-o-klimatu--preview-csob-link-gzneqhyt.web.app/o-nas)

Přidání odkazu z loga ČSOB na csob.cz

---

collections/_explainers/bezemisni-energetika-cr-1-scenare.md
collections/_pages/index.md
plugins-local/filter-sort-fallback.rb

[Preview](https://cz-fakta-o-klimatu--preview-updated-metadata-gbcabvnb.web.app/)

Brát v potaz datum aktualizace v sekci Nejnovější

---

collections/_pages/vlny-veder-obce.md

[Preview](https://cz-fakta-o-klimatu--preview-vlny-veder-mailing-e03mcwp1.web.app/vlny-veder-obce)

Stránka k vlnám veder

---

collections/_infographics/energetika/elektrina-na-osobu-eu.md
collections/_infographics/energetika/elektrina-oze-eu.md

- Jedna podstatná oprava (2023 -> 2024)
- Drobné ladění formulací / linků okolo Ember (navíc obě grafiky sladěné na stejné formulace)

Drobné opravy v grafikách mixů EU
